### PR TITLE
Added error handling for Nvidia GPU, fixed some pylint errors

### PR DESCRIPTION
**Pull request by JeremiahPetersen**
I added a few error handling options for Nvidia GPU, and fixed some pylint errors. (trailing whitespaces, missing doc string)  I added # pylint: disable=line-too-long & # pylint: disable=C0103 so single letter variables and lines over 100 char will pass pylint.  Let me know if you want to include these changes.  I would like to get the pylint back to passing, as it was before my previous PR.

### CODE REVIEW

**Comment by JeremiahPetersen** [comment]
I will continue work on this today to get pylint passing

**Comment by JeremiahPetersen** [comment]
Added pylint disable comments for line > 100 char, import error (winreg), single letter variables (C0103) & Catching too general exception (W0718)

"# pylint: disable=line-too-long, import-error"
"# pylint: disable=C0103, W0718"

Everything is functioning correctly on my end.  Every once in a while I will get a terminal output of 

 [Running] python -u "c:\Users\...\Desktop\SYSIG\sysig.py"
An error occurred: 0

I added an error handling block with traceback error to determine what this is, but was unable to determine.  Happens 1 out of 10 times when running code.  Code continues to run and functions correctly on all tabs.  The error only appears at the beginning of running the script (10% of the time).  No other terminal outputs occur while the code is running.  I am unsure if this is only on my end.

**Comment by diamant3** [comment]
Thank you for fixing the pylint. I really appreciate it!

I just noticed that you disabled some pylint checks. Sorry, but I'm not a fan of disabling the pylint in the source code. Please remove it. I'll lower the pylint score in the workflow and merge it later. Thanks again!

**Comment by JeremiahPetersen** [comment]
No worries at all!  Let me know if you want anything else adjusted.

**Comment by diamant3** [comment]
Hi, I tried to lower the pylint score but it didn't fix

I suggest to do this following:
- if method like `dpg.add_text()`, you can do like this:
```python
dpg.add_text(
    arg1,
    arg2,
    arg3)
```
- use a meaningful and snake_case style when naming a variable even when doing alias(`as` keyword) 

search the pylint checks's name/number in https://pylint.readthedocs.io/en/latest/, they have correct code to implement, thanks!

**Comment by JeremiahPetersen** [comment]
Ah, thanks for the feedback!  I will work more on it in the next 48 hours and message when it is ready for review.

**Comment by JeremiahPetersen** [comment]
I have cleaned up the graphics section and the code is ready for review.  I think I got everything fixed in the graphics section, let me know if I missed anything!

**Comment by diamant3** [comment]
> I have cleaned up the graphics section and the code is ready for review.  I think I got everything fixed in the graphics section, let me know if I missed anything!

LGTM! I'll merge this later, thank you!

**Comment by diamant3** [comment]
Thanks!

**Pull request merged**
